import { Node, Protocol } from "@/types";

export const researchNodes: Node[] = [
  {
    id: "r1",
    category: "research",
    efficiency: 0,
    outputType: "solar",
    cost: { hydro: 3 },
    effectType: "discount",
    effectValue: 1,
    effectTarget: "solar",
  },
  {
    id: "r2",
    category: "research",
    efficiency: 0,
    outputType: "solar",
    cost: { hydro: 1, plasma: 1, neural: 2 },
  },
  {
    id: "r3",
    category: "research",
    efficiency: 1,
    outputType: "solar",
    cost: { plasma: 4 },
    effectType: "reclaim",
    effectValue: 1,
  },
  {
    id: "r4",
    category: "research",
    efficiency: 0,
    outputType: "hydro",
    cost: { plasma: 3 },
  },
  {
    id: "r5",
    category: "research",
    efficiency: 0,
    outputType: "hydro",
    cost: { solar: 1, plasma: 2, neural: 1 },
    effectType: "discount",
    effectValue: 1,
    effectTarget: "hydro",
  },
  {
    id: "r6",
    category: "research",
    efficiency: 1,
    outputType: "hydro",
    cost: { neural: 4 },
  },
  {
    id: "r7",
    category: "research",
    efficiency: 0,
    outputType: "plasma",
    cost: { neural: 3 },
    effectType: "multiplier",
    effectValue: 2,
    effectTarget: "plasma",
  },
  {
    id: "r8",
    category: "research",
    efficiency: 0,
    outputType: "plasma",
    cost: { solar: 2, hydro: 1, neural: 1 },
  },
  {
    id: "r9",
    category: "research",
    efficiency: 1,
    outputType: "plasma",
    cost: { solar: 4 },
  },
  {
    id: "r10",
    category: "research",
    efficiency: 0,
    outputType: "neural",
    cost: { solar: 3 },
  },
  {
    id: "r11",
    category: "research",
    efficiency: 0,
    outputType: "neural",
    cost: { solar: 1, hydro: 1, plasma: 2 },
    effectType: "swap",
    effectValue: 2,
  },
  {
    id: "r12",
    category: "research",
    efficiency: 1,
    outputType: "neural",
    cost: { hydro: 4 },
    effectType: "discount",
    effectValue: 1,
    effectTarget: "neural",
  },
  {
    id: "r13",
    category: "research",
    efficiency: 0,
    outputType: "solar",
    cost: { hydro: 2, plasma: 1, neural: 1 },
  },
  {
    id: "r14",
    category: "research",
    efficiency: 0,
    outputType: "hydro",
    cost: { solar: 1, plasma: 1, neural: 2 },
  },
  {
    id: "r15",
    category: "research",
    efficiency: 0,
    outputType: "plasma",
    cost: { solar: 1, hydro: 2, neural: 1 },
  },
  {
    id: "r16",
    category: "research",
    efficiency: 0,
    outputType: "neural",
    cost: { solar: 2, hydro: 1, plasma: 1 },
  },
];

export const productionNodes: Node[] = [
  {
    id: "p1",
    category: "production",
    efficiency: 2,
    outputType: "solar",
    cost: { hydro: 5, plasma: 3 },
  },
  {
    id: "p2",
    category: "production",
    efficiency: 2,
    outputType: "solar",
    cost: { plasma: 4, neural: 4 },
  },
  {
    id: "p3",
    category: "production",
    efficiency: 3,
    outputType: "solar",
    cost: { hydro: 6, neural: 3 },
    effectType: "multiplier",
    effectValue: 2,
    effectTarget: "solar",
  },
  {
    id: "p4",
    category: "production",
    efficiency: 2,
    outputType: "hydro",
    cost: { solar: 3, plasma: 5 },
  },
  {
    id: "p5",
    category: "production",
    efficiency: 2,
    outputType: "hydro",
    cost: { solar: 4, neural: 4 },
    effectType: "reclaim",
    effectValue: 1,
  },
  {
    id: "p6",
    category: "production",
    efficiency: 3,
    outputType: "hydro",
    cost: { plasma: 6, solar: 3 },
  },
  {
    id: "p7",
    category: "production",
    efficiency: 2,
    outputType: "plasma",
    cost: { hydro: 5, neural: 3 },
    effectType: "multiplier",
    effectValue: 2,
    effectTarget: "plasma",
  },
  {
    id: "p8",
    category: "production",
    efficiency: 2,
    outputType: "plasma",
    cost: { hydro: 4, solar: 4 },
  },
  {
    id: "p9",
    category: "production",
    efficiency: 3,
    outputType: "plasma",
    cost: { neural: 6, hydro: 3 },
  },
  {
    id: "p10",
    category: "production",
    efficiency: 2,
    outputType: "neural",
    cost: { plasma: 5, solar: 3 },
    effectType: "swap",
    effectValue: 3,
  },
  {
    id: "p11",
    category: "production",
    efficiency: 2,
    outputType: "neural",
    cost: { plasma: 4, hydro: 4 },
  },
  {
    id: "p12",
    category: "production",
    efficiency: 3,
    outputType: "neural",
    cost: { solar: 6, plasma: 3 },
    effectType: "reclaim",
    effectValue: 1,
  },
  {
    id: "p13",
    category: "production",
    efficiency: 2,
    outputType: "solar",
    cost: { hydro: 4, plasma: 3, neural: 2 },
  },
  {
    id: "p14",
    category: "production",
    efficiency: 2,
    outputType: "hydro",
    cost: { solar: 4, plasma: 2, neural: 3 },
  },
  {
    id: "p15",
    category: "production",
    efficiency: 2,
    outputType: "plasma",
    cost: { solar: 3, hydro: 4, neural: 2 },
  },
  {
    id: "p16",
    category: "production",
    efficiency: 2,
    outputType: "neural",
    cost: { solar: 2, hydro: 3, plasma: 4 },
  },
];

export const networkNodes: Node[] = [
  {
    id: "n1",
    category: "network",
    efficiency: 4,
    outputType: "solar",
    cost: { hydro: 7, plasma: 4, neural: 3 },
    effectType: "multiplier",
    effectValue: 3,
    effectTarget: "solar",
  },
  {
    id: "n2",
    category: "network",
    efficiency: 4,
    outputType: "solar",
    cost: { plasma: 8, neural: 5 },
  },
  {
    id: "n3",
    category: "network",
    efficiency: 5,
    outputType: "solar",
    cost: { hydro: 9, plasma: 6 },
    effectType: "reclaim",
    effectValue: 1,
  },
  {
    id: "n4",
    category: "network",
    efficiency: 4,
    outputType: "hydro",
    cost: { solar: 7, plasma: 3, neural: 4 },
  },
  {
    id: "n5",
    category: "network",
    efficiency: 4,
    outputType: "hydro",
    cost: { solar: 8, neural: 5 },
    effectType: "swap",
    effectValue: 4,
  },
  {
    id: "n6",
    category: "network",
    efficiency: 5,
    outputType: "hydro",
    cost: { plasma: 9, solar: 6 },
  },
  {
    id: "n7",
    category: "network",
    efficiency: 4,
    outputType: "plasma",
    cost: { hydro: 7, neural: 4, solar: 3 },
    effectType: "multiplier",
    effectValue: 3,
    effectTarget: "plasma",
  },
  {
    id: "n8",
    category: "network",
    efficiency: 4,
    outputType: "plasma",
    cost: { hydro: 8, solar: 5 },
  },
  {
    id: "n9",
    category: "network",
    efficiency: 5,
    outputType: "plasma",
    cost: { neural: 9, hydro: 6 },
    effectType: "discount",
    effectValue: 2,
    effectTarget: "plasma",
  },
  {
    id: "n10",
    category: "network",
    efficiency: 4,
    outputType: "neural",
    cost: { plasma: 7, solar: 4, hydro: 3 },
  },
  {
    id: "n11",
    category: "network",
    efficiency: 4,
    outputType: "neural",
    cost: { plasma: 8, hydro: 5 },
    effectType: "reclaim",
    effectValue: 2,
  },
  {
    id: "n12",
    category: "network",
    efficiency: 5,
    outputType: "neural",
    cost: { solar: 9, plasma: 6 },
    effectType: "multiplier",
    effectValue: 3,
    effectTarget: "neural",
  },
  {
    id: "n13",
    category: "network",
    efficiency: 4,
    outputType: "solar",
    cost: { hydro: 6, plasma: 5, neural: 4 },
  },
  {
    id: "n14",
    category: "network",
    efficiency: 4,
    outputType: "hydro",
    cost: { solar: 6, plasma: 4, neural: 5 },
  },
  {
    id: "n15",
    category: "network",
    efficiency: 4,
    outputType: "plasma",
    cost: { solar: 5, hydro: 6, neural: 4 },
  },
  {
    id: "n16",
    category: "network",
    efficiency: 4,
    outputType: "neural",
    cost: { solar: 4, hydro: 5, plasma: 6 },
  },
];

export const controlNodes: Node[] = [
  {
    id: "c1",
    category: "control",
    efficiency: 1,
    outputType: "solar",
    cost: { hydro: 2, plasma: 2 },
    effectType: "swap",
    effectValue: 2,
  },
  {
    id: "c2",
    category: "control",
    efficiency: 1,
    outputType: "solar",
    cost: { plasma: 3, neural: 2 },
    effectType: "reclaim",
    effectValue: 1,
  },
  {
    id: "c3",
    category: "control",
    efficiency: 3,
    outputType: "solar",
    cost: { hydro: 5, plasma: 4 },
    effectType: "discount",
    effectValue: 2,
    effectTarget: "solar",
  },
  {
    id: "c4",
    category: "control",
    efficiency: 1,
    outputType: "hydro",
    cost: { solar: 2, plasma: 2 },
    effectType: "multiplier",
    effectValue: 2,
    effectTarget: "hydro",
  },
  {
    id: "c5",
    category: "control",
    efficiency: 1,
    outputType: "hydro",
    cost: { solar: 3, neural: 2 },
  },
  {
    id: "c6",
    category: "control",
    efficiency: 3,
    outputType: "hydro",
    cost: { solar: 5, neural: 4 },
    effectType: "swap",
    effectValue: 3,
  },
  {
    id: "c7",
    category: "control",
    efficiency: 1,
    outputType: "plasma",
    cost: { hydro: 2, neural: 2 },
    effectType: "reclaim",
    effectValue: 1,
  },
  {
    id: "c8",
    category: "control",
    efficiency: 1,
    outputType: "plasma",
    cost: { solar: 2, hydro: 3 },
    effectType: "discount",
    effectValue: 1,
    effectTarget: "plasma",
  },
  {
    id: "c9",
    category: "control",
    efficiency: 3,
    outputType: "plasma",
    cost: { solar: 4, hydro: 5 },
  },
  {
    id: "c10",
    category: "control",
    efficiency: 1,
    outputType: "neural",
    cost: { solar: 2, plasma: 2 },
    effectType: "multiplier",
    effectValue: 2,
    effectTarget: "neural",
  },
  {
    id: "c11",
    category: "control",
    efficiency: 1,
    outputType: "neural",
    cost: { hydro: 3, plasma: 2 },
    effectType: "swap",
    effectValue: 2,
  },
  {
    id: "c12",
    category: "control",
    efficiency: 3,
    outputType: "neural",
    cost: { hydro: 4, plasma: 5 },
    effectType: "reclaim",
    effectValue: 1,
  },
  {
    id: "c13",
    category: "control",
    efficiency: 1,
    outputType: "solar",
    cost: { hydro: 3, neural: 2 },
  },
  {
    id: "c14",
    category: "control",
    efficiency: 1,
    outputType: "hydro",
    cost: { solar: 2, neural: 3 },
  },
  {
    id: "c15",
    category: "control",
    efficiency: 1,
    outputType: "plasma",
    cost: { hydro: 2, solar: 3 },
  },
  {
    id: "c16",
    category: "control",
    efficiency: 1,
    outputType: "neural",
    cost: { solar: 3, hydro: 2 },
  },
];

export const protocols: Protocol[] = [
  {
    id: "pr1",
    name: "Solar Amplification",
    efficiency: 4,
    requirements: { solar: 5, hydro: 3 },
    effect: "Double solar output generation",
    claimed: false,
  },
  {
    id: "pr2",
    name: "Hydro Cascade",
    efficiency: 4,
    requirements: { hydro: 5, plasma: 3 },
    effect: "Collect +1 energy per turn",
    claimed: false,
  },
  {
    id: "pr3",
    name: "Plasma Matrix",
    efficiency: 4,
    requirements: { plasma: 5, neural: 3 },
    effect: "Reserve nodes for free",
    claimed: false,
  },
  {
    id: "pr4",
    name: "Neural Network",
    efficiency: 4,
    requirements: { neural: 5, solar: 3 },
    effect: "Swap any 2 energies freely",
    claimed: false,
  },
  {
    id: "pr5",
    name: "Quantum Stability",
    efficiency: 4,
    requirements: { solar: 4, hydro: 4 },
    effect: "No energy limit this game",
    claimed: false,
  },
  {
    id: "pr6",
    name: "Fusion Core",
    efficiency: 4,
    requirements: { hydro: 4, plasma: 4 },
    effect: "+2 efficiency per node",
    claimed: false,
  },
  {
    id: "pr7",
    name: "Dark Matter Link",
    efficiency: 4,
    requirements: { plasma: 4, neural: 4 },
    effect: "Draw extra node each turn",
    claimed: false,
  },
  {
    id: "pr8",
    name: "Singularity Point",
    efficiency: 4,
    requirements: { neural: 4, solar: 4 },
    effect: "All nodes cost -1 energy",
    claimed: false,
  },
  {
    id: "pr9",
    name: "Universal Bridge",
    efficiency: 4,
    requirements: { solar: 3, hydro: 3, plasma: 3 },
    effect: "Flux counts as any 2 energy",
    claimed: false,
  },
  {
    id: "pr10",
    name: "Infinity Conduit",
    efficiency: 4,
    requirements: { hydro: 3, plasma: 3, neural: 3 },
    effect: "Claim second protocol for free",
    claimed: false,
  },
];

export function createShuffledDeck(cards: Node[]): Node[] {
  const deck = [...cards];
  for (let i = deck.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [deck[i], deck[j]] = [deck[j], deck[i]];
  }
  return deck;
}
